### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by forsomefun** [beaston02/MFCRecorder#25]
old recorder doesn't seem to be working with PM2 
However the new recorder does. Not sure how the files are different.

**Comment by forsomefun** [comment]
Actually both seem to be working now. It seemed like files where not be made. But I ran both recorders again, and they both worked.

The new recorder seems to log better.

What is the difference between the two?

**Comment by sKanoodle** [comment]
@forsomefun the new script is more structured. If you looked into it, it's only 29 lines long and uses classes where I put all the program logic. This should make further development and fixing bugs easier.

The new script is still in need for debugging, thats why the logging is quite verbose. That might get changed in the future. The main difference between both scripts is: the new one doesn't have the web-frontend included yet. The rest should be more or less implemented.
