### ISSUE TITLE
Camscore and Tags not recording

### ISSUE THREAD

**Issue by longsack** [beaston02/MFCRecorder#31]
Title says it all, i have checked tags some are being used on the site also camscore is set low 1000 so it should start, am i missing something in my config file?

explained a little about this issue, new system debian 8, python3.6 it was working on 7 but installed 8 to fix another issue... testing that one now.

**Comment by beaston02** [comment]
Would you mind posting your config file? You could pm it to me on reddit (same username there, beaston02). 

My first thought would be the min_viewers setting might be blocking the recordings. 

One other thing just came to mind. Are you running the latest version of mfcauto.py? The command to install/upgrade should be in the readme. I'm replying from my phone otherwise I would post it here. I know older versions won't pull tags correctly.

**Comment by beaston02** [comment]
python3.6 -m pip install --upgrade git+https://github.com/ZombieAlex/mfcauto.py@master

Run that to confirm you are on the latest.

**Comment by longsack** [comment]
[paths]
wishlist_path = /var/modellist/mfc/wanted.json
save_directory = /var/just_recorded
directory_structure = {path}/{model}_{auto}_from_myfreecams_{year}.{month}.{day}_{hour}.{minutes}.{seconds}.mp4
completed_directory =

[settings]
check_interval = 20
min_space = 1
post_processing_command =
post_processing_thread_count = 1
min_viewers = 0
stop_viewers = 0
priority = 0

[auto_recording]
viewers = 300
auto_stop_viewers = 200
score = 1000
newer_than_hours = 0
tags = asian,asia
min_tags = 1
tag_viewers = 0
tag_stop_viewers = 0

[web]
port = 8778
enabled = True
username = 
password = 

i removed username/password.

**Comment by longsack** [comment]
Cloning https://github.com/ZombieAlex/mfcauto.py (to master) to /tmp/pip-0f8pf_vt-build
Installing collected packages: mfcauto
  Found existing installation: mfcauto 0.1.5
    Uninstalling mfcauto-0.1.5:
      Successfully uninstalled mfcauto-0.1.5
  Running setup.py install for mfcauto ... done
Successfully installed mfcauto-1.0.0


i did a fresh install, but maybe I wasn't?

**Comment by beaston02** [comment]
Everything looks good... I notice it Successfuly installed mfcauto-1.0.0, but I'm guessing that's just based on the version not being updated in the code. 

That didn't by chance fix it, did it?

**Comment by longsack** [comment]
That did the trick!!!!!
