### ISSUE TITLE
Post Processing

### ISSUE THREAD

**Issue by gg2ezz** [beaston02/MFCRecorder#35]
So I see you have in the conf that you can use post processing for example movetogoogledrive.sh I was just wondering how can I achieve this cant seem to figure out how to do it I basically want the files to be rclone moved after the download is complete to my google drive. Cant seem to understand the parameters any help?

So my capture path is /mfc and i have /mfc/modelname and wanting to rclone move all model name folders in mfc folder to google drive.

I know this isn't an issue but don't know where else to ask for help on this.
Thanks

**Comment by sKanoodle** [comment]
I have an example script that retrieves the parameters from postprocessing: https://github.com/beaston02/MFCRecorder/blob/master/scripts/postProcessing.py

I don't see why you would rclone every time a recording finished though. Rclone is a copy tool, that only copies new files to a destination by itself. You don't need to tell it which files are new. Maybe it would be better to rclone once every day or something. To only rclone finished files then, you could use the completed_directory config option and move recordings there after they finished, then rclone them from there.
