### ISSUE TITLE
[Request] Creation of 'Develop' branch

### ISSUE THREAD

**Issue by David-Eilers** [beaston02/MFCRecorder#37]
Hello @beaston02 and @sKanoodle,

I want to propose the creation of a Develop branch.

All future development would be done in this branch and all future pull request would be made against this branch.

The creation of a develop branch would lead to a cleaner and more bug free (hopefully) master branch, all new releases or features would be merged from the develop branch into the master branch when they're ready.

This means we could also use github tags to preserve past releases.

I hope you will find this useful.

**Comment by David-Eilers** [comment]
@beaston02 @sKanoodle , Any update on this?

**Comment by sKanoodle** [comment]
When i developed the new client, I used a branch just for that. I would suggest instead of one development-branch for everything, we should create a feature-branch for single features.

**Comment by David-Eilers** [comment]
Yes i know, but against which branch should pull requests be done? People who are not a collaborators cannot create branches so they have to file a pull request against one of the existing branches or asks for the creation of a feature branch. at this moment master is the only branch that exists and thus all pull requests are done against master which possibly clutters the master branch and introduces bugs.

Just my two cents, i would like to hear how you would implement this.

**Comment by secrbn** [comment]
Completely agree with implementing gitflow.  This way the master branch stays stable and bug fixes and features can be done against the development branch.
