### ISSUE TITLE
interval variable not used

### ISSUE THREAD

**Issue by Gimpoid** [beaston02/MFCRecorder#4]
Sorry if this isnt the correct place to post this I noticed the interval variable wasn't being used in the code. Where I assume its meant to be used its hardcoded to 20. If I edited line 144 to "for i in range(interval, 0, -1):" that fixed the issue.

Thanks for creating a very useful script it works great and the video quality is top notch!

**Comment by beaston02** [comment]
Good find. Thank you for pointing it out. I just made the change. 

Im glad youre enjoying it!
