### ISSUE TITLE
New Install Error

### ISSUE THREAD

**Issue by ttid150** [beaston02/MFCRecorder#46]
Just did a clean install and I'm getting some errors, I tried restarting from a clean archive and I'm still getting the same errors. I'm running Cent OS 7 .

Here's the errors that I'm getting;
```
[root@server script]# python3.6 mfcrecorder.py
Traceback (most recent call last):
  File "mfcrecorder.py", line 7, in <module>
    import classes
  File "/home/mfc/script_/classes/__init__.py", line 1, in <module>
    import classes.config
  File "/home/mfc/script_/classes/config.py", line 8, in <module>
    import classes.helpers as helpers
  File "/home/mfc/script_/classes/helpers.py", line 9, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**Comment by nvcld** [comment]
I encountered the same error. For now you can install numpy this way: type `python3 -m pip install numpy` if you haven't pip the first google results for centos python3 pip numpy work.

**Comment by ttid150** [comment]
Solved, I tried to the numpy install but I wrote the command wrong so it didn't work the first time.
