### ISSUE TITLE
Enhancements for file processing

### ISSUE THREAD

**Issue by sKanoodle** [beaston02/MFCRecorder#6]
I have two small scripts that I wrote to further simplify working with this nice project of yours.

The first one generates the wanted list from a dictionary containing the model ID and the model name. This would give more insight as to which models are already in the wanted list (and since it is written in python you can comment entries out). On top of that it creates a symlink for each model directory to make the model ID directories easier to access.

The second script regards the raw video files. Encoding the videos makes them shrink in size and also more playable (e.g. raw videos didnt show duration in vlc). There is also a built in function to merge files in case a recording was interrupted with a customizable timespan to decide whether or not to merge videos.

I dont really know if there is any demand in those scripts. If there is let me know, I am more than happy to share them, maybe you can include them in the repository or something.

**Comment by Gimpoid** [comment]
I was actually thinking of the merge function as being useful as sometimes I have noticed I end up with 5-10 videos after an evening and some were very short and not worth encoding. I know the current script has a section for encoding completed files but I am not sure how to use it yet so perhaps a short guide might be useful?

Thinking of a good place to store the videos maybe in google photos as they allow "unlimited" space for uploads if you let it compress them for you. Also not sure how to automate uploads to there though.

**Comment by sKanoodle** [comment]
Well, the command for completed files would not be very useful here, because at this point we dont know if there will be another video right after that. My script basically scans the folder for video files and detects mergable files. This would be perfect to run it in a cronjob maybe every night.

for now i will just share the code here if you are interested. It requires ffmpeg to be installed and you can set a few things at the start of the script. It also relies on mtime to determine when the file was last written to, so if you want to use this script, dont move the video files beforehand.

```python
#!/usr/bin/env python3
import os, subprocess, argparse, time
from datetime import datetime, timedelta

#directory with model ID subdirectories
sourcefolder = "/home/user/MFC/src"
#directory to save the encoded files in
destinationfolder = "/home/user/MFC/encoded"
#logfile path (leave as empty string if no logging is desired)
logfilepath = "/home/user/MFC/encoding.log"
#{0} is the absoulte source file path, {1} is the absolute target file path
ffmpegcommand = "ffmpeg -loglevel quiet -i {0} -vcodec libx264 -crf 23 {1}"
#extension of the encoded file
extension = ".mp4"
#{0} is the absolute path of the file with parts to concat, {1} is the absolute target file path
ffmpegmergecommand = "ffmpeg -v error -f concat -safe 0 -i {0} -c copy {1}"
#filename must not exist already directly in the sourcefolder
tmpconcatfilename = "concat.mp4"
#max time in minutes that is allowed between the end of a video and the beginning of the next video to concatinate them
concatmaxtime = 60
#time in minutes that has to have passed since the last modification of a recording to include it for encoding
#(should always be larger than concatmaxtime, otherwise the file will be encoded even if a next file would have been eligible to be concatinated to it)
ignorefreshvideostime = 60
datetimeformat = "{:%Y-%m-%d %X}"

parser = argparse.ArgumentParser()
parser.add_argument("-d", "--dryrun", action="store_true", dest="dryrun", help="Simulates encoding of all files in the source folder. Size and duration of some videos might differ, because there is no concatination performed, although the status output expects concatinated videos. It will therefore only show size and duration of the first file that should be concatinated.")
args = parser.parse_args()

def log_and_print(string):
    if not args.dryrun and logfilepath:
        with open(logfilepath, "a") as file:
            file.write(string + "\n")
    print(string)

def format_seconds(totalseconds):
    totalseconds = int(totalseconds)
    totalminutes, seconds = divmod(totalseconds, 60)
    totalhours, minutes = divmod(totalminutes, 60)
    return "{0}:{1:02d}:{2:02d}".format(totalhours, minutes, seconds)

def get_video_length_seconds(path):
    if not os.path.exists(path):
        return 0
    lengthraw = subprocess.check_output("ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 {0}".format(path), shell=True)
    try:
        return float(lengthraw.strip())
    except:
        return 0

def get_file_encoding_infos(sourcepath):
    if args.dryrun:
        if not os.path.exists(sourcepath):
            return {"source": sourcepath, "target": "", "size": 0, "length": 0}
    
    #relies on set structure: sourcefolder/modelID/video
    directory, file = os.path.split(sourcepath)
    filename, ext = os.path.splitext(file)
    return {"source": sourcepath,
        "target": os.path.join(destinationfolder, os.path.basename(directory), filename + extension),
        "size": os.path.getsize(sourcepath) / 1024 / 1024,
        "length": get_video_length_seconds(sourcepath)}

def parse_creation_time(path):
    return datetime.strptime(os.path.basename(path)[:19], "%Y.%m.%d_%H.%M.%S")

def calculate_eta(starttime, progress):
    if progress <= 0:
        return "calculating ETA"
    if progress >= 1:
        return "done at {}".format(datetimeformat.format(datetime.now()))
    passedseconds = (datetime.now() - starttime).total_seconds()
    estimatedduration = passedseconds / progress
    return "ETA: {}".format(datetimeformat.format(starttime + timedelta(seconds=estimatedduration)))

def concat_files(files, name):
    log_and_print("{0} merging into {1}:".format(datetimeformat.format(datetime.now()), name))
    for file in files:
        log_and_print("[{:>10,.2f} MiB] [{}] {}".format(os.path.getsize(file) / 1024 / 1024, format_seconds(get_video_length_seconds(file)), file))
    mergefilepath = os.path.join(os.path.dirname(name), "tempmergefile.txt")
    tmp = os.path.join(sourcefolder, tmpconcatfilename)
    ffmpeg = ffmpegmergecommand.format(mergefilepath, tmp)
    if args.dryrun:
        print("[DRYRUN] would create mergefile {0}".format(mergefilepath))
        print("[DRYRUN] would run {0}".format(ffmpeg))
        print("[DRYRUN] would move {0} to {1}".format(tmp, name))
    else:
        #create mergefile with info about parts
        mergefile = open(mergefilepath, "w")
        for file in files:
            mergefile.write("file '{0}'\n".format(file))
        mergefile.close()
        #concat videos
        os.system(ffmpeg)
        #delete source parts
        for file in files:
            os.remove(file)
        #move concatinated video from temp location to final location
        os.rename(tmp, name)
        #remmove the mergefile
        os.remove(mergefilepath)
        

def merge_files_in_model_directory(directory):
    #the files need to be scanned into a list first, so we can look ahead to the next file
    entries = []
    for file in sorted(os.listdir(directory)):
        filepath = os.path.join(directory, file)
        if not file.endswith(".mp4"):
            continue
        entries.append({"creation": parse_creation_time(file),
            "modification": datetime.fromtimestamp(os.path.getmtime(filepath)),
            "file": filepath})

    #now we can traverse the files we found and check if the next file is directly following the previous and merge them if necessary
    filestoencode = []
    concatlist = []
    for i in range(len(entries)):
        #last run of the loop, we dont want further execution here, just adding the last file/performing the last concatination
        if i == len(entries) - 1:
            #make sure the latest file is not written to anymore
            if entries[i]["modification"] + timedelta(minutes=ignorefreshvideostime) > datetime.now():
                log_and_print("ignoring {0} and possible previous mergable files".format(entries[i]["file"]))
                #exit the loop and dont add the files in the concat list to filestoencode, so we can merge them the next time this script runs
                break
            #last file is not being merged, add it to the filestoencode list
            if len(concatlist) < 2:
                filestoencode.append(get_file_encoding_infos(entries[i]["file"]))
            #last file is being merged, merge and then add merged file to the filestoencode list
            else:
                concat_files(concatlist, concatlist[0])
                filestoencode.append(get_file_encoding_infos(concatlist[0]))
                concatlist = []
            break
        #print("{3} {0} {1} {2}".format(entries[i]["creation"], entries[i]["modification"], entries[i]["file"], i))
        m = entries[i]["modification"]
        c = entries[i + 1]["creation"]
        #current file has a following up file that needs to be merged
        if m < c and m + timedelta(minutes=concatmaxtime) > c:
            if not entries[i]["file"] in concatlist:
                concatlist.append(entries[i]["file"])
            concatlist.append(entries[i + 1]["file"])
        #there is nothig more to be merged
        else:
            #concatlist is empty, so treat the file as normal video to be encoded
            if len(concatlist) < 1:
                filestoencode.append(get_file_encoding_infos(entries[i]["file"]))
                continue
            #concat list has a single entry, should never happen, because there is nothing to concat
            elif len(concatlist) == 1:
                log_and_print("single file in concat list?????? {0}".format(concatlist[0]))
            #concat the files and then encode the resulting new video
            else:
                concat_files(concatlist, concatlist[0])
                filestoencode.append(get_file_encoding_infos(concatlist[0]))
                concatlist = []
    return filestoencode

def merge_and_encode_everything():
    print("finding files to encode ...", end="\r")

    entries = []
    #each ID in the source folder
    for id in os.listdir(sourcefolder):
        #ID-directory
        dir = os.path.join(sourcefolder, id)
        if os.path.isdir(dir):
            entries.extend(merge_files_in_model_directory(dir))

    index = 0
    #hack to prevent division by 0
    totalsize = max(sum([entry["size"] for entry in entries]), 1)
    sizedone = 0
    #hack to prevent division by 0
    totallength = max(sum([entry["length"] for entry in entries]), 1)
    lengthdone = 0
    starttime = datetime.now()
    progresstemplate = "    {0:,.2f}/{1:,.2f} MiB ({2:.2%}) [{7}] | {3}/{4} ({5:.2%}) [{8}] | [{6}]"
    
    def get_stats():
        return [sizedone,
            totalsize,
            sizedone / totalsize,
            format_seconds(lengthdone),
            format_seconds(totallength),
            lengthdone / totallength,
            format_seconds((datetime.now() - starttime).total_seconds()),
            calculate_eta(starttime, sizedone / totalsize),
            calculate_eta(starttime, lengthdone / totallength)]

    for entry in entries:
        #create encoding target folder in case it doesnt exist
        if not args.dryrun and not os.path.exists(os.path.dirname(entry["target"])):
            os.makedirs(os.path.dirname(entry["target"]))
        index += 1
        log_and_print("{5} {0}: [{1:>10,.2f} MiB] [{2}] source: {3}, target: {4}"
            .format(datetimeformat.format(datetime.now()), entry["size"], format_seconds(entry["length"]), entry["source"], entry["target"], "{0}/{1}".format(index, len(entries)).rjust(9)))
        #print with carriage return at the end, so that this line can be overwritten by the next print
        print(progresstemplate.format(*get_stats()), end="\r")
        sizedone += entry["size"]
        lengthdone += entry["length"]
        if not args.dryrun:
            os.system(ffmpegcommand.format(entry["source"], entry["target"]))
            os.remove(entry["source"])

    #final progress, should always show 100%
    print(progresstemplate.format(*get_stats()))

merge_and_encode_everything()
```

**Comment by beaston02** [comment]
Thanks for the info! I'll definitely look at them if you don't mind (I see the one was posted above). 

I had actually thought about adding a time limit to continue recording to the same file, say if the model leaves (goes "away", into a group chat, private chat...) and then comes back with in two minutes (I would make this configurable) then it would continue to write to the end of the previous file. 

I also thought about having an option to run a command (or script) on a file if it is shorter than a specified duration. Ie if it's a 2 or less, the user could just delete it with the appropriate command. Another thought, and the one I would be more likely to go with, is to include the duration and size of the video file in the arguments sent to the post processing script, so the user could include conditional statements based on the duration and/or size. 

I'm out of town at the moment, but I'll look into this further when I get home and have some free time.

**Comment by sKanoodle** [comment]
I am just leaving the second script here then, too. It's just the first thing i came up with, so it's most likely not perfect, but surely a nice helper to keep that wanted list together. Both scripts are only tested on linux btw, so no idea if they work under windows.

```python
#!/usr/bin/env python
import os, sys

models = {123: "name1",
    345: "name2"}

encodedfilesdir = "/home/user/MFC/encoded"
symlinkdir = "/home/user/MFC/models"
wantedfile = "/home/user/MFC/wanted.txt"

if not os.path.exists(symlinkdir):
    os.makedirs(symlinkdir)

for file in os.listdir(symlinkdir):
    if os.path.islink(os.path.join(symlinkdir, file)):
        os.remove(os.path.join(symlinkdir, file))

#create symlinks to find recordings by model name
for id, name in models.items():
    os.symlink(os.path.join(encodedfilesdir, str(id)), os.path.join(symlinkdir, name))

#create wanted file
wanted = open(wantedfile, "w")
for id in models:
    wanted.write("{0}\n".format(id))

```

**Comment by Gimpoid** [comment]
Just wondering if there was any progress on having the merge feature added to the core code? Have had a few times where I woke up to find a directory full of 50+ 1 minute long clips as I assume the model was constantly going offline due to privates or them having connection issues.

**Comment by beaston02** [comment]
I haven't put a lot of thought into adding the feature to the script. It comes to mind every now and again, but I've had a lot going on lately, so I haven't put much thought into the script in general. It comes to mind now and again, and I try to think of the best way to implement it. I feel like to do it proper, I'll need to implement a MySQL database to better track more data. My thought is to track the status of the models whenever it changes. Right now it's simply "if they're in free chat (public chat room)...." I'm thinking maybe a "if they go from public to private, or to group, and if private/group is less than x minutes then merge files" and on the other hand, if they go offline, then don't merge... I'll make it user configurable to an extent, but I don't want to go too crazy with the options either. Personally, I don't know if it's a feature I would particularly care for because it is separate recordings. It will have the clear transition from one recording to another, and I feel like the short videos would better be deleted, or simply kept for the sake of having the "complete collection". However, I don't think because that's my preference that others shouldn't have it their way, but it does limit my motivation to get it implemented. 

I'm completely open to input on how others feel it should be implemented, I would love to hear it. Things like what conditions would warrant merging files (maximum amount of time between recordings, maximum length of videos, models status, or whatever else....). 

Also, as for merging videos you already have, ffmpeg can do that. I can't remember the exact command, but googling should turn up a result fairly quick. You will need to pass a list of files to be merged which can be from a command (like ls on Unix systems, but I don't know windows at all). If you're using the default naming scheme, they should already be in a oldest to newest order when sorted by name, but you will want to make sure it is correct. 

I'm replying from my phone so please excuse any typos or auto corrects. Also, I had a few destractions, so I apologize if it reads weird or I started rambling too much!!! Lol.

**Comment by sKanoodle** [comment]
@Gimpoid I guess I could post an alternated script that just merges the files and moves them without encoding. The earliest time I could do that is saturday though.

**Comment by Gimpoid** [comment]
@sKanoodle that would also be great as the current script works fine for me I would just want it to skip the encoding part and just merges the files and moves them.

@beaston02 I wouldnt make it too complicated you could even just implement the code posted above and have an option for it to encode or just merge the files. I think its options for merging everything within 60 minutes is quite reasonable. Better to keep it simple and not worry too much about model statuses and just the timestamp between the files.

**Comment by sKanoodle** [comment]
@Gimpoid I finally got around to modify the encoding script. If you want to skip encoding, all you have to do now is to add the -c flag.
<details>
<summary>click to view code</summary>

```python
#!/usr/bin/env python3
import os, subprocess, argparse, time
from datetime import datetime, timedelta

#directory with model ID subdirectories
sourcefolder = "/home/user/MFC/src"
#directory to save the encoded files in
destinationfolder = "/home/user/MFC/encoded"
#logfile path (leave as empty string if no logging is desired)
logfilepath = "/home/user/MFC/encoding.log"
#{0} is the absoulte source file path, {1} is the absolute target file path
ffmpegcommand = "ffmpeg -loglevel quiet -i {0} -vcodec libx264 -crf 23 {1}"
#extension of the encoded file
extension = ".mp4"
#{0} is the absolute path of the file with parts to concat, {1} is the absolute target file path
ffmpegmergecommand = "ffmpeg -v error -f concat -safe 0 -i {0} -c copy {1}"
#filename must not exist already directly in the sourcefolder
tmpconcatfilename = "concat.mp4"
#max time in minutes that is allowed between the end of a video and the beginning of the next video to concatinate them
concatmaxtime = 60
#time in minutes that has to have passed since the last modification of a recording to include it for encoding
#(should always be larger than concatmaxtime, otherwise the file will be encoded even if a next file would have been eligible to be concatinated to it)
ignorefreshvideostime = 60
datetimeformat = "{:%Y-%m-%d %X}"

parser = argparse.ArgumentParser()
parser.add_argument("-d", "--dryrun", action="store_true", dest="dryrun", help="Simulates encoding of all files in the source folder. Size and duration of some videos might differ, because there is no concatination performed, although the status output expects concatinated videos. It will therefore only show size and duration of the first file that should be concatinated.")
parser.add_argument("-c", "--copy", action="store_true", dest="copy", help="Only copies the video files instead of encoding them, but still merges them beforehand.")
args = parser.parse_args()

def log_and_print(string):
    if not args.dryrun and logfilepath:
        with open(logfilepath, "a") as file:
            file.write(string + "\n")
    print(string)

def format_seconds(totalseconds):
    totalseconds = int(totalseconds)
    totalminutes, seconds = divmod(totalseconds, 60)
    totalhours, minutes = divmod(totalminutes, 60)
    return "{0}:{1:02d}:{2:02d}".format(totalhours, minutes, seconds)

def get_video_length_seconds(path):
    if not os.path.exists(path):
        return 0
    lengthraw = subprocess.check_output("ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 {0}".format(path), shell=True)
    try:
        return float(lengthraw.strip())
    except:
        return 0

def get_file_encoding_infos(sourcepath):
    if args.dryrun:
        if not os.path.exists(sourcepath):
            return {"source": sourcepath, "target": "", "size": 0, "length": 0}
    
    #relies on set structure: sourcefolder/modelID/video
    directory, file = os.path.split(sourcepath)
    filename, ext = os.path.splitext(file)
    return {"source": sourcepath,
        "target": os.path.join(destinationfolder, os.path.basename(directory), filename + extension),
        "size": os.path.getsize(sourcepath) / 1024 / 1024,
        "length": get_video_length_seconds(sourcepath)}

def parse_creation_time(path):
    return datetime.strptime(os.path.basename(path)[:19], "%Y.%m.%d_%H.%M.%S")

def calculate_eta(starttime, progress):
    if progress <= 0:
        return "calculating ETA"
    if progress >= 1:
        return "done at {}".format(datetimeformat.format(datetime.now()))
    passedseconds = (datetime.now() - starttime).total_seconds()
    estimatedduration = passedseconds / progress
    return "ETA: {}".format(datetimeformat.format(starttime + timedelta(seconds=estimatedduration)))

def concat_files(files, name):
    log_and_print("{0} merging into {1}:".format(datetimeformat.format(datetime.now()), name))
    for file in files:
        log_and_print("[{:>10,.2f} MiB] [{}] {}".format(os.path.getsize(file) / 1024 / 1024, format_seconds(get_video_length_seconds(file)), file))
    mergefilepath = os.path.join(os.path.dirname(name), "tempmergefile.txt")
    tmp = os.path.join(sourcefolder, tmpconcatfilename)
    ffmpeg = ffmpegmergecommand.format(mergefilepath, tmp)
    if args.dryrun:
        print("[DRYRUN] would create mergefile {0}".format(mergefilepath))
        print("[DRYRUN] would run {0}".format(ffmpeg))
        print("[DRYRUN] would move {0} to {1}".format(tmp, name))
    else:
        #create mergefile with info about parts
        mergefile = open(mergefilepath, "w")
        for file in files:
            mergefile.write("file '{0}'\n".format(file))
        mergefile.close()
        #concat videos
        os.system(ffmpeg)
        #delete source parts
        for file in files:
            os.remove(file)
        #move concatinated video from temp location to final location
        os.rename(tmp, name)
        #remmove the mergefile
        os.remove(mergefilepath)
        

def merge_files_in_model_directory(directory):
    #the files need to be scanned into a list first, so we can look ahead to the next file
    entries = []
    for file in sorted(os.listdir(directory)):
        filepath = os.path.join(directory, file)
        if not file.endswith(".mp4"):
            continue
        entries.append({"creation": parse_creation_time(file),
            "modification": datetime.fromtimestamp(os.path.getmtime(filepath)),
            "file": filepath})

    #now we can traverse the files we found and check if the next file is directly following the previous and merge them if necessary
    filestoencode = []
    concatlist = []
    for i in range(len(entries)):
        #last run of the loop, we dont want further execution here, just adding the last file/performing the last concatination
        if i == len(entries) - 1:
            #make sure the latest file is not written to anymore
            if entries[i]["modification"] + timedelta(minutes=ignorefreshvideostime) > datetime.now():
                log_and_print("ignoring {0} and possible previous mergable files".format(entries[i]["file"]))
                #exit the loop and dont add the files in the concat list to filestoencode, so we can merge them the next time this script runs
                break
            #last file is not being merged, add it to the filestoencode list
            if len(concatlist) < 2:
                filestoencode.append(get_file_encoding_infos(entries[i]["file"]))
            #last file is being merged, merge and then add merged file to the filestoencode list
            else:
                concat_files(concatlist, concatlist[0])
                filestoencode.append(get_file_encoding_infos(concatlist[0]))
                concatlist = []
            break
        #print("{3} {0} {1} {2}".format(entries[i]["creation"], entries[i]["modification"], entries[i]["file"], i))
        m = entries[i]["modification"]
        c = entries[i + 1]["creation"]
        #current file has a following up file that needs to be merged
        if m < c and m + timedelta(minutes=concatmaxtime) > c:
            if not entries[i]["file"] in concatlist:
                concatlist.append(entries[i]["file"])
            concatlist.append(entries[i + 1]["file"])
        #there is nothig more to be merged
        else:
            #concatlist is empty, so treat the file as normal video to be encoded
            if len(concatlist) < 1:
                filestoencode.append(get_file_encoding_infos(entries[i]["file"]))
                continue
            #concat list has a single entry, should never happen, because there is nothing to concat
            elif len(concatlist) == 1:
                log_and_print("single file in concat list?????? {0}".format(concatlist[0]))
            #concat the files and then encode the resulting new video
            else:
                concat_files(concatlist, concatlist[0])
                filestoencode.append(get_file_encoding_infos(concatlist[0]))
                concatlist = []
    return filestoencode

def merge_and_encode_everything():
    print("finding files to encode ...", end="\r")

    entries = []
    #each ID in the source folder
    for id in os.listdir(sourcefolder):
        #ID-directory
        dir = os.path.join(sourcefolder, id)
        if os.path.isdir(dir):
            entries.extend(merge_files_in_model_directory(dir))

    index = 0
    #hack to prevent division by 0
    totalsize = max(sum([entry["size"] for entry in entries]), 1)
    sizedone = 0
    #hack to prevent division by 0
    totallength = max(sum([entry["length"] for entry in entries]), 1)
    lengthdone = 0
    starttime = datetime.now()
    progresstemplate = "    {0:,.2f}/{1:,.2f} MiB ({2:.2%}) [{7}] | {3}/{4} ({5:.2%}) [{8}] | [{6}]"
    
    def get_stats():
        return [sizedone,
            totalsize,
            sizedone / totalsize,
            format_seconds(lengthdone),
            format_seconds(totallength),
            lengthdone / totallength,
            format_seconds((datetime.now() - starttime).total_seconds()),
            calculate_eta(starttime, sizedone / totalsize),
            calculate_eta(starttime, lengthdone / totallength)]

    for entry in entries:
        #create encoding target folder in case it doesnt exist
        if not args.dryrun and not os.path.exists(os.path.dirname(entry["target"])):
            os.makedirs(os.path.dirname(entry["target"]))
        index += 1
        log_and_print("{5} {0}: [{1:>10,.2f} MiB] [{2}] source: {3}, target: {4}"
            .format(datetimeformat.format(datetime.now()), entry["size"], format_seconds(entry["length"]), entry["source"], entry["target"], "{0}/{1}".format(index, len(entries)).rjust(9)))
        #print with carriage return at the end, so that this line can be overwritten by the next print
        print(progresstemplate.format(*get_stats()), end="\r")
        sizedone += entry["size"]
        lengthdone += entry["length"]
        if not args.dryrun:
            if not args.copy:
                #actual call to encode the video
                os.system(ffmpegcommand.format(entry["source"], entry["target"]))
                os.remove(entry["source"])
            else:
                #only move the video file without encoding
                os.rename(entry["source"], entry["target"])

    #final progress, should always show 100%
    print(progresstemplate.format(*get_stats()))

merge_and_encode_everything()
```
</details>

**Comment by Gimpoid** [comment]
Seems to work well thankyou. The only issue I found was it crashes if it encounters a file with size 0. Is it possible to automatically delete or ignore those files?

e.g. 

[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000000bf9000] moov atom not found
E:\MFC\Save\20642513\2017.08.26_15.28.39_MsPrincessJ.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "merge.py", line 215, in <module>
    merge_and_encode_everything()
  File "merge.py", line 169, in merge_and_encode_everything
    entries.extend(merge_files_in_model_directory(dir))
  File "merge.py", line 132, in merge_files_in_model_directory
    concat_files(concatlist, concatlist[0])
  File "merge.py", line 80, in concat_files
    log_and_print("[{:>10,.2f} MiB] [{}] {}".format(os.path.getsize(file) / 1024 / 1024, format_seconds(get_video_length_seconds(file)), file))
  File "merge.py", line 46, in get_video_length_seconds
    lengthraw = subprocess.check_output("ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 {0}".format(path), shell=True)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 E:\MFC\Save\20642513\2017.08.26_15.28.39_MsPrincessJ.mp4' returned non-zero exit status 1.

**Comment by Gimpoid** [comment]
Looks like it doesnt like the new file formatting for auto recorded items.

Traceback (most recent call last):
  File "merge.py", line 215, in <module>
    merge_and_encode_everything()
  File "merge.py", line 169, in merge_and_encode_everything
    entries.extend(merge_files_in_model_directory(dir))
  File "merge.py", line 112, in merge_files_in_model_directory
    entries.append({"creation": parse_creation_time(file),
  File "merge.py", line 66, in parse_creation_time
    return datetime.strptime(os.path.basename(path)[:19], "%Y.%m.%d_%H.%M.%S")
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'VIEWERS_2017.08.31_' does not match format '%Y.%m.%d_%H.%M.%S'

**Comment by sKanoodle** [comment]
@beaston02 do you think we should include the merge and encode script into the repository? Posting a new slightly different version in the comments here is not exactly a good kind of version control. And since you said you dont know how to merge the files automatically yet, maybe just say in the readme to use this script in a cron job?

**Comment by beaston02** [comment]
@sKanoodle I absolutely agree. I was thinking doing a "scripts" directory containing any user contributed scripts (yours being the first). Im still not real familiar with github and what all non owners/creators can contribute, but if you're able to upload them, feel free. If not, Is the last posted one what you would like to be added? Also, feel free to edit the readme and add a section describing your script if you would like. Im on my computer, but just briefly at the moment. Ill look at creating a scripts directory and adding it to the readme when I get back to my computer again in an hour or two. Im going to see if I cant fix this last issue first though. 

Thanks again for all the contributions. Its definitely helped me learn. If you ever wanted to message me directly, I'm beaston02 on reddit if you're on there also. Im not aware of any PMs here on GitHUb

**Comment by beaston02** [comment]
@sKanoodle @Gimpoid 

I thought the last reported issue was in the MFCRecorder.py script, and just noticed it is in the merge script. It looks like the file naming option changed how it parsed the filename. Im about to start my workout, and I can take a look at it after Im done if @sKanoodle has not yet done so. 

As always, thank you for reporting, and contributing!

**Comment by beaston02** [comment]
@Gimpoid 

I modified the script to strip out the conditional names when parsing the file for its date/time. I did not have any files to test it on, but I believe it should work. The modified version can be found [here](https://github.com/beaston02/MFCRecorder/blob/master/scripts/merge.py)

@sKanoodle 

I added the merge + encode script into a scripts directory. I havent even looked over the code entirely, but the different variables seem simple enough to understand, so Ill see about adding a section to the readme file breaking it down. Please feel free to make any changes. 
Would it be worth implementing a way to pull the files modified time to get the date/time rather than pulling it from the filename? I did a quick google search, and it seems to be different for Mac, Linux, and Windows machines, so might be a bit of work, and Im personally unable to test on windows. I suppose we could see if it is requested.

**Comment by sKanoodle** [comment]
@beaston02 I already pull the mtime (modified time) from the files. I read the file name to have the creation time as well, since there is nothing like that as metadata on linux. Now, if i would take the video length into account, I could
I. ignore the creation time and get around the parsing from file name, or
II. ignore the mtime (which is changed when files are moved), so the script would work on moved files as well.

For better parsing i will now look into an approach with regex. When using the video length here, I could also already delete files with a length of 0 (maybe with a safety so that the file size also has to be 0, to account for faulty metadata)

**Comment by sKanoodle** [comment]
@Gimpoid parsing the creation date should be easier now, I added regex support (can be customized). That fixed the issue with the prefixes from auto recording, they are just ignored now.

I added the -r (or --remove) flag to delete faulty videos, per default they will be ignored from now on. Use the flag on your own risk.

**Comment by Gimpoid** [comment]
@sKanoodle Testing out the new version it seems good though I did bump into one weird thing. It was spamming these errors for pages and pages. It didnt show up in the encoding log so I am not sure while file triggered the error or if its an issue.

[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358230 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358231 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358232 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358233 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358234 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358235 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358236 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358237 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358238 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358239 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358240 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358241 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358242 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358243 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358244 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358245 is out of range for mov/mp4 format
[mp4 @ 0000000000e2e780] Application provided duration: 8232656774 / timestamp: 8652358246 is out of range for mov/mp4 format

**Comment by sKanoodle** [comment]
@Gimpoid did it flag any files with content as faulty? that should be in the log. If this is just an info and doesn't lead to an error, I will look into not letting ffprobe display output.

But yes, the recorded files are not the best, that's why I dedicate all that processing power to encode them afterwards, that fixes most of the playback issues.

**Comment by Gimpoid** [comment]
@sKanoodle I didn't see any flagged with errors in the logs so maybe it was just informational. Ill keep a closer eye next time. Normally I just kick it off and go do something its only I happened to look while it was occuring.

Yeah I usually encode the ones I want to keep on another machine as the one downloading is pretty slow so thats why I like them merged first. I can scan through to see if anything worthwhile occured if not delete if its a keeper then encode.
