### ISSUE TITLE
Hangs after about 8 hours.

### ISSUE THREAD

**Issue by Gimpoid** [beaston02/MFCRecorder#8]
Not sure if anyone else is having this issue but I just recently tried to run this overnight as I was planning to possibly run it 24/7 in future. What I noticed is if I started it at about midnight before bed it would eventually hang at around 8 or 9am and the console would stop updating at the part where its connecting to the xchat server. Downloads that were already in progress seemed to continue downloading but it would no longer do the check for new models.

I am running on Windows 10 x64
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32

Ill try it later in a Ubuntu Virtual Machine when I have time to set one up.

Last line usually looks like.

[F[F[F[F[2017-08-11 08:22:00,983] Connecting to MyFreeCams chat server xchat22...

**Comment by dhearns** [comment]
Same here. Been running it on Raspbian for a few weeks now and have to kill & restart daily. Not a big issue for me though because i had no way of automating prior to MFCRecorder. Sometimes when none of my favorites are online i proactively restart the script.

**Comment by Gimpoid** [comment]
How well does it run on Raspbian? I was actually considering buying a Pi and running that 24/7 as a server for this as it seems like a cheap option that wouldnt use too much power. Can it handle 24/7 uptime without overheating and burning down my house hehe? Any tips for doing it? Do you just use an external HD for the data to save the SD card from too many writes and access the files over the network from your main machine? Do you do any video encoding on the Pi or copy it over to the main box for that kinda stuff?

**Comment by dhearns** [comment]
@Gimpoid It runs well actually.  I  run MFC Recorder, SMRecorder, CAM4Recorder, CamSodaRecorder & CaptureBate simultaneously 24/7 on my Pi 3 & it's also my VPN when I'm away from home.  Across the scripts it's recording 13 models at the moment, and the processor's at 0-13%. It never gets warm, maybe because VNC/SSH into it and it's mounted in an open GeauxRobot case.  I haven't had any SD corruption and I've been running CaptureBate, recording to the same MicroSD as the OS for 2 yrs now, as it fills up I move the files to my NAS. ~1 yr ago I upgraded to the Samsung  EvoPlus 256GB MicroSD that i got for free with the Note 7 - with no problems. I only encode the CaptureBate files on the Pi before I move them to the NAS because the audio isn't playable otherwise & that encoding utilizes 30-40% CPU.  All the others I've been leaving as-is, although some won't show a duration and seek is slow. 

I believe it's possible to automate like stopping/starting processes with Supervisor based on a schedule or restarting stopped processes. It would be cool if MFCRecorder could somehow restart itself whenever it's idle but I don't have the know-how.

**Comment by beaston02** [comment]
I'm out of town at the moment so I can't be much help right now (I have no access to a computer, and only briefly have access to my phone will I'm outside of the secure area I'm currently working). Can you make sure you have the latest version of mfcauto installed? 

I don't actually run this script, so I don't know if this is a common issue or not (other than you two both having it). The first thing that comes to mind though, is the mfcauto possibly being the older version which would have connection issues after sometime, although what your describing doesn't sound like its the same issue as it was causing before.

**Comment by Gimpoid** [comment]
No rush with the fix it can certainly wait till your back at home :)

I found this related to restarting a script from within itself which may be an ok workaround if the root cause cant be found. Looks like it would need to close the open files its writing to first. I'm not really good enough to make any changes myself.

https://blog.petrzemek.net/2014/03/23/restarting-a-python-script-within-itself/

Regarding the mfcauto updating I just run python3.5 -m pip install --upgrade git+https://github.com/ZombieAlex/mfcauto.py@master to update it right? 0.1.3 is the version on my system.

Thanks again for creating a useful script! 👍

**Comment by Gimpoid** [comment]
Got an actual error this morning.

> [2017-08-12 08:55:24,176] Connecting to MyFreeCams chat server xchat59...
Task exception was never retrieved
future: <Task finished coro=<Client.connect() done, defined at C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py:170> exception=ConnectionRefusedError(10061, "Connect call failed ('207.229.72.149', 8100)")>
Traceback (most recent call last):
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py", line 176, in connect
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.format(selected_server), 8100)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 776, in create_connection

>

**Comment by Gimpoid** [comment]
Ok just got another error this time only after about 2-3 hours. I think these are related to the MFC website having issues as I just loaded up the site and it has a maintinence page up.

> [2017-08-12 11:49:47,933] Connecting to MyFreeCams chat server xchat68...
Task exception was never retrieved
future: <Task finished coro=<Client.connect() done, defined at C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py:170> exception=ConnectionRefusedError(10061, "Connect call failed ('207.229.75.23', 8100)")>
Traceback (most recent call last):
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py", line 176, in connect
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.format(selected_server), 8100)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 10061] Connect call failed ('207.229.75.23', 8100)

>

**Comment by beaston02** [comment]
I just got back in town and I believe I fixed what was causing the issue. I have not had time to test it long enough for sure, but you can try installing my for of mfcauto.py with:

`python3.5 -m pip install --upgrade git+https://github.com/beaston02/mfcauto.py@master`

I currently have it running, and it seems to connect fine, but again, its only been running for about 10 minutes at this point so I dont know what will happen in 8 hours from now...

I believe what was going on is the script was attempting to connect to a server, failed, and would attempt to connect to that same server again over and over again, and continuing to fail, causing the script to hang (I assume the sever is down). 

Again, this was a very quick fix, but if you want to test it, run the code above and see if it changes anything. I will be getting to bed before long, and I will post an update on if I encountered the problem by the morning.

**Comment by beaston02** [comment]
I have had it running with no issues on my mac, and on ubuntu for about 12 hours now. 

I was exhausted yesterday when I made the changes to mfcauto.py, and the changes I made should have no effect on the issue (I dont think). I was not thinking clearly and tried to do a quick fix. If you have not tested it, feel free, but again, I dont think it will fix the issue. I will try to look into this more over the weekend.

**Comment by Gimpoid** [comment]
It seems stable for me also. I have a feeling the original issue was related to the MFC servers going down and like you said it would hang while trying to reconnect. Hard to test without the servers having issues.

Would running the script and then disconnecting the internet for a few minutes then reconnecting it again be a good way to test?

**Comment by beaston02** [comment]
I don't think disconnecting and reconnecting will do it. I think that would register as a failed connection and should retry. I feel like the connection may just be hanging (ass supposed to getting a "connected" or a "disconnected" signal). Again, this is part of the mfcauto.py module which I didn't write, and is honestly beyond my level of knowledge. It uses asyncio which I have the slightest understanding of. The particular command, I believe, should timeout after 120 seconds but it doesn't seem to for whatever reason. Maybe someone with more knowledge could chime in or maybe have a solution. Also, an issue could be opened there, but where it's such a rare occurrence, I have a feeling it's going to be difficult to troubleshoot. I could be wrong though. 

I may poke around at it and see if I can't figure it out.

**Comment by Gimpoid** [comment]
Happened again last night. For the last week or so never happened so maybe as we think the MFC servers went down or the one chat one did.

[F[K0 model(s) are being recorded. Next check in 2 seconds
[F[K0 model(s) are being recorded. Next check in 1 seconds
[F[F[F[F[2017-08-26 04:40:28,363] Connecting to MyFreeCams chat server xchat65...
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2017-08-26 04:43:39,863] Connecting to MyFreeCams chat server xchat90...
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2017-08-26 04:44:11,005] Connecting to MyFreeCams chat server xchat49...
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2017-08-26 04:44:42,035] Connecting to MyFreeCams chat server xchat85...
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2017-08-26 04:45:13,034] Connecting to MyFreeCams chat server xchat32...
Task exception was never retrieved
future: <Task finished coro=<Client.connect() done, defined at C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py:170> exception=ConnectionRefusedError(10061, "Connect call failed ('207.229.72.232', 8100)")>
Traceback (most recent call last):
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py", line 176, in connect
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.format(selected_server), 8100)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 10061] Connect call failed ('207.229.72.232', 8100)

**Comment by beaston02** [comment]
I made some changes to my fork of mfcauto. Again, Im not familiar with asyncio and how it all functions, so Im hoping this helps, but kind of throwing things at the wall in hopes something sticks. 

I added a timeout to essentially give up after so much time trying to connect. I tested it with .01 sec timeout, and it would fail, and the script would continue running, so Im hoping it will also work for the conditions you and others have been running into. I set it to a 5 second delay on the timeout, but I could change that if needed. It seems most connections take < .5 seconds, so I imagine 5 seconds should be plenty. 


If you could install async-timeout with:

`python3.5 -m pip install async-timeout`

and install my fork of mfcauto with:

`python3.5 -m pip install --upgrade git+https://github.com/beaston02/mfcauto.py@master`

and let me know how it works for you. I will hold off on recommending the changes to the main fork of mfcauto until more testing has been done. 

I appreciate the help.

**Comment by Gimpoid** [comment]
Thanks I will give it a try later today.

**Comment by Gimpoid** [comment]
So I updated using your instructions below and it still seems to hang.

[F[K0 model(s) are being recorded. Next check in 3 seconds
[F[K0 model(s) are being recorded. Next check in 2 seconds
[F[K0 model(s) are being recorded. Next check in 1 seconds
[F[F[F[F[2017-08-30 03:21:26,736] Connecting to MyFreeCams chat server xchat124...
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2017-08-30 03:25:15,908] Connecting to MyFreeCams chat server xchat30...
Task exception was never retrieved
future: <Task finished coro=<Client.connect() done, defined at C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py:174> exception=ConnectionRefusedError(10061, "Connect call failed ('207.229.72.230', 8100)")>
Traceback (most recent call last):
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py", line 183, in connect
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.format(selected_server), 8100)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 10061] Connect call failed ('207.229.72.230', 8100)

**Comment by beaston02** [comment]
I made some changes in hopes of fixing this issue. I moved the portion which connects to MFCs servers to the getModels.py file. It now calls this file and will terminate it if it hasnt finished within 5 seconds (shouldn't take more than about 1 second normally)

I added the use of the blessings library, so make sure it is installed, and update to my latest branch of mfcauto

`pip3 install -r requirements.txt`
`pip3 install --upgrade git+https://github.com/beaston02/mfcauto.py@master`

**Comment by beaston02** [comment]
I believe this was fixed a while back, so I'm closing this issue.
Thanks again for all the input and testing!
